version: 2

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    branches:
      only:
        - circleci-project-setup
    executor: android/android
        
    steps:
      - checkout
      - run:
          command: ./gradlew build

